title: "build.log"
author: "Mitchell"
description: "Technical build log."
baseurl: "" 
url: "https://m11tch.github.io"
permalink: /blog/:year/:month/:day/:title.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
design:
  font: "Outfit"
  accent_color: "#3b82f6"
